name: citizens01
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+25

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_bloc: ^6.0.6
  http: ^0.12.2
  flutter_secure_storage: ^3.3.5
  requests: ^3.3.0
  gradient_app_bar: ^0.0.1
  flutter_screenutil: ^2.3.1
  steps: ^1.0.1
  url_launcher: ^5.6.0
  equatable: ^1.2.5
  mask_text_input_formatter: ^1.1.0
  # sms: ^0.2.4 
  flushbar: ^1.10.4
  beauty_textfield: ^0.0.1
  hexcolor: ^1.0.6
  flutter_map: ^0.10.1+1
  latlong: ^0.6.1
  location: ^2.3.5
  transparent_image: ^1.0.0
  file_picker: ^2.1.5
  firebase_messaging: ^7.0.3
  flutter_local_notifications: ^3.0.2
  shared_preferences: ^0.5.12+4


  flutter_localizations:
    sdk: flutter
  

  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/animal.png
     - images/coronavirus_1.png
     - images/family_3Si7Zvx.png
     - images/life_1.png
     - images/logo.png
     - images/logo12.png
     - images/maintenance_1_jjWxT9B.png
     - images/man_1.png
     - images/school_1_So7Qd9q.png
     - images/traffic_1_YA9b6Wo.png
     - images/trash_1.png
     - images/trees_2_K4b3Dvy.png
     - images/Vector1.png
     - images/Vector2.png
     - images/wheelchair_1.png
     - images/phone.png
     - images/Vector3.png
     - images/Vector4.png
     - images/submitreq.png
     - images/bell.png
     - images/agenda.png
     - images/user.png
     - images/track.png
     - images/vectordown.png
     - images/upload.png
     - images/maintenance_1.png
     - images/school_1.png
     - images/translations/
     - images/citizen3.png
     - images/bground.png
     - images/bground2.png
     - images/logo_new.png
     - images/Group.png
     - images/buildings.png
     - images/life.png
     - images/school-bag_CFMjsoZ.png
     - images/blocks_vLGwcJm.png
     - images/agenda_2_1.png
     - images/109aktobe.png
     - images/bg.png
     - images/v1.png
     - images/v2.png
  







   
     
     
     

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#"images/icon/citizen2.png"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon/logo_new2.png"
  